### ISSUE TITLE
Idea for use with Vagrant

### ISSUE THREAD

**Issue by funkflute** [dzava/atom-artisan#2]
I have my Laravel dev instance inside a vagrant box. Could there be a way to run the command through the ssh shell? I can run the commands from my command line like this:

`vagrant ssh -c "php /var/www/html/artisan cache:clear"`

maybe instead of your "php executable" it could be a search / replace string:

`php %artisan%`

so it could be configured in many ways like for a vagrant VM:

`vagrant ssh -c "php /var/www/html/%artisan%"`

or for non-vagrant, just a way to change the default php location

`/etc/php-v71/php %artisan%`

**Comment by dzava** [comment]
Create a script and set it as the PHP executable option.

```bash
#!/usr/bin/env bash

vagrant ssh -c "php /var/www/html/artisan ${@:2}"
```

**Comment by funkflute** [comment]
Okay, cool. I had to parse out the working directory to get vagrant to work, here's what I got for anyone else who needs it:

```
#!/usr/bin/env bash

PWD=$(echo "${@:1}" | sed -E 's|(.*)/artisan (.*)|\1|g')
VAGRANT_CWD=$PWD vagrant ssh -c "php /var/www/html/artisan ${@:2}"
```
