### ISSUE TITLE
Feature request - multiple commands at once.

### ISSUE THREAD

**Issue by kikoseijo** [dzava/atom-artisan#3]
Firstable: Gratz for this lovely plugin!

Have cleaned most of the aliases on the .bash_profile

Been trying to work it out myself but could not figure it alone.
Any chance we can run couple of commands at once?
 
Like for example:
`php artisan clear-compiled && php artisan migrate:refresh && php artisan db:seed`

It does some sort of check for command existence, been trying to add the command in the custom_commads.json, but refuses to load and because of this will not load any other command, must delete the file and then reopen Atom, otherwise your commands wont load either.

***Posible enhancement*** Make sure your commands loads even when custom_commands.json have unknown commands.

This is one of the example been trying to load trough `CustomCommands.json`:

```json
{
  "name": "myCommand",
  "command": "clear-compiled && php artisan migrate:refresh && php artisan db:seed",
  "needsInput": false,
  "caption": "",
  "showInPanel": true
}
```

Hope it makes sense, we can still use the bash Aliases, just wondering!

Happy days!
Kiko Seijo.

**Comment by dzava** [comment]
You have two options: 

- use a custom script like https://github.com/dzava/atom-artisan/issues/2 to handle running the commands
- register a custom command in your init file and [dispatch](https://atom.io/docs/api/v1.19.5/CommandRegistry#instance-dispatch) the commands you want to run.

If you didn't know you can refresh and seed the database by passing the `--seed` option to the `migrate:refresh` command. You just have to override the default command and ask for input.

I will push a new version that fixes the custom commands error.

**Comment by kikoseijo** [comment]
Exellent, you did my day, i missed the --seed option.

Very kind of you!
